language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "eaSFCAOHDFoinw0Pj+0QHAMnpJGeUZcNGJ5Di2Ed8D2LhT17FpmOoLTKAdPfBeODFlyKpH5cLP1yEtLZVJfuTdriyp9QtXGZ/A8zNRCQvtwAalRLEzfu0Ww96fsDTFbl7XJLyyjwm3n0jdn6nDtwnWLK1149+eRMJCclEwKLPIcQfn11+GSKGMy9qkRK4U0Xwheel2BNSMdD0MPBlu0rclvbRzUeOe+b8lyQjMMOicH3nWUtEygOS1MZcRfyaoM827u3yJWkkGlj6Xpa8kCQ4BVDWtOxiwulzLe0S8riFwDxSdRoUF2yAARlRwSP85LJ125JY6Ha5JfiOURRofEwdhS/xxCbOzpBHdgbtQHm7zh1eSic0XZpu311jPHOCBj4P10aHc9eVieAqHAjIgpD29OTumepQd3aD/tCb3Q7eeR6kYIOpIIr+Il7hLXdaYuqwQr8EsIrMA3CDC72y+L1FgDJdz1eacwVfxkM4xNgg9Y0JhMzB8yoIXR3Bfiz1m7wQZkMwto4JBE2MUegtm7zg3HrNftYl8KrQdk2uFQy4MFIZzAQpNWsoPkwWGZpUUDlXb8m3AgjbAtZTJBx3kutD1PaSUlSni54yTOtPByJZKd59vEEQQkXLfv70rgJsm8qU3SFK6L/t3Hx4d1+bMk0Wa0Et2aq7dH8kAUPVSYS/ks="